{
  config,
  ...
}:
{
  users.mutableUsers = false;

  users.groups = {
    aaron = { };
    docker = { };
  };

  users.users.aaron = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    home = "/home/aaron";
    isNormalUser = true;
    extraGroups = [
      "aaron"
      "users"
      "networkmanager"
      "wheel"
      "docker"
    ];
  };
}
